services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    api:
        build: .
        ports:
            - 8080:8080
        environment:
            API_PORT: 8080
            #API_DATABASE_URL: host=db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable
            API_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
        depends_on:
            - db
volumes:
    pgdata: {}
