# https://taskfile.dev

version: '3'

tasks:
  tidy:
    cmds:
      - go mod tidy

  build:
    deps:
      - tidy
    cmds:
      - go build -o api ./cmd/api

  run:
    deps:
      - build
    cmds:
      - ./api

  test:
    deps:
      - build
    cmds:
      - go test ./...

  new-migration: # task new-migration -- <table name>
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}

  migrate-up: # migrate -path ./migrations -database "pgx5://postgres:postgres@0.0.0.0:5432/postgres?sslmode=disable" -verbose up
    cmds:
      - migrate -path ./migrations -database "pgx5://postgres:postgres@0.0.0.0:5432/postgres?sslmode=disable" -verbose up